spring:
  datasource:
    url: jdbc:postgresql://localhost:45888/postgres
    username: postgres
    password: Dota2Kruto!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    properties:
      hibernate:
        format_sql: true